language: cpp
os: linux
dist: xenial
sudo: required
language: python
python: "2.7"

git:
  submodules: true

install:
  - sudo apt-get install whois -y
  - pip install -r pydot

script:
  - do_generate_config.py switches.json
